---
- name: install on web server
  hosts: mvn
  become: yes

  tasks:
  - name: install maven
    apt:
      name: maven
      state: present
    
  - name: install git
    apt:
      name: git
      state: present

  - name: remove old git clone
    file:
      path: /home/morg/boxfuse-sample-java-war-hello
      state: absent

  - name: clone git
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git

#  - name: copy fucking pom.xml
#    copy:
#      src: /home/morg/boxfuse-sample-java-war-hello
#      dest:


  - name: mvn package
    command: mvn -f /boxfuse-sample-java-war-hello package

- name: copy fucking pom.xml
